const sentences = [
    `Hello, how are you today?",Bonjour, comment ça va?`,
    `こんにちは、お元気ですか？`,
    `안녕하세요, 오늘 어떻게 지내세요?`,
    `你好，你今天好吗？`,
    `I love the smell of fresh coffee in the morning.`,
    `J'aime l'odeur du café frais le matin.`,
    `朝の新しいコーヒーの香りが好きです。`,
    `아침에 신선한 커피 냄새가 좋아요.`,
    `我喜欢早上新鲜咖啡的味道。`,
    `Where is the nearest metro station?`,
    `Où est la station de métro la plus proche?`,
    `一番近い地下鉄駅はどこですか？`,
    `가장 가까운 지하철역은 어디에요?`,
    `最近的地铁站在哪里？`,
    `Can you recommend a good restaurant in this area?`,
    `Pouvez-vous recommander un bon restaurant dans le coin ?`,
    `このエリアで良いレストランをお勧めできますか？`,
    `이 지역에서 좋은 레스토랑을 추천해 주실 수 있나요?`,
    `你能推荐这个地区的好餐厅吗？`,
    `I enjoy reading books by the fireplace.`,
    `J'aime lire des livres près de la cheminée.`,
    `暖炉のそばで本を読むのが好きです。`,
    `벽난로 옆에서 책 읽는 것을 즐겨요.`,
    `我喜欢在壁炉旁边读书。`,
    `What time does the museum open?`,
    `À quelle heure ouvre le musée ?`,
    `博物館は何時に開きますか？`,
    `박물관은 몇 시에 문을 열어요?`,
    `博物馆几点开门？`,
    `How do you say "thank you" in Japanese?`,
    `Comment dit-on "merci" en japonais ?`,
    `「ありがとう」と言うのは日本語で何と言いますか？`,
    `일본어로 "감사합니다"는 어떻게 말해요?`,
    `在日语中怎么说“谢谢”？`,
    `Let's meet at the park at 3 PM.`,
    `Retrouvons-nous au parc à 15h.`,
    `午後3時に公園で会いましょう。`,
    `오후 3시에 공원에서 만나요.`,
    `下午3点在公园见吧。`,
    `What is your favorite season?`,
    `Quelle est votre saison préférée ?`,
    `あなたのお気に入りの季節は何ですか？`,
    `당신이 가장 좋아하는 계절은 무엇인가요?`,
    `你最喜欢的季节是哪个？`,
    `I need directions to the nearest hospital.`,
    `J'ai besoin d'indications pour l'hôpital le plus proche.`,
    `一番近い病院への行き方を教えてください。`,
    `가장 가까운 병원으로 가는 방법을 알려주세요.`,
    `去最近的医院需要怎么走？`,
    `Do you have any siblings?`,
    `As-tu des frères et sœurs ?`,
    `兄弟姉妹はいますか？`,
    `혹시 형제 자매가 있나요?`,
    `你有兄弟姐妹吗？`,
    `Let's try the sushi at that new restaurant.`,
    `Essayons les sushis dans ce nouveau restaurant.`,
    `あの新しいレストランで寿司を試してみましょう。`,
    `그 새로운 식당에서 스시를 먹어보자.`,
    `咱们试试那家新餐厅的寿司吧。`,
    `How do you say "I love you" in Korean?`,
    `Comment dit-on "je t'aime" en coréen ?`,
    `「愛してる」と韓国語でどう言いますか？`,
    `한국어로 "사랑해"는 어떻게 말해요?`,
    `用韩语怎么说“我爱你”？`,
    `The Great Wall of China is a UNESCO World Heritage Site.`,
    `La Grande Muraille de Chine est un site du patrimoine mondial de l'UNESCO.`,
    `中国の万里の長城はユネスコの世界遺産です。`,
    `중국의 만리장성은 유네스코 세계유산입니다.`,
    `中国的长城是联合国教科文组织的世界遗产。`,
    `What is the capital city of France?`,
    `Quelle est la capitale de la France ?`,
    `フランスの首都は何ですか？`,
    `프랑스의 수도는 어디에요?`,
    `法国的首都是哪里？`,
    `Can you recommend a good movie to watch?`,
    `Pouvez-vous recommander un bon film à regarder ?`,
    `良い映画を教えていただけますか？`,
    `보기 좋은 영화 하나 추천해 주세요.`,
    `你能推荐一部好电影吗？`,
    `I enjoy learning new languages.`,
    `J'aime apprendre de nouvelles langues.`,
    `新しい言語を学ぶのが好きです。`,
    `새로운 언어를 배우는 것을 즐겨요.`,
    `我喜欢学习新语言。`,
    `What is the weather like today?`,
    `What is the most famous landmark in your country?`,
    `Quel est le monument le plus célèbre de votre pays ?`,
    `あなたの国で最も有名な名所は何ですか？`,
    `당신 나라에서 가장 유명한 랜드마크는 무엇인가요?`,
    `你国最著名的地标是什么？`,
    `How do you celebrate traditional holidays with your family?`,
    `Comment célèbrez-vous les fêtes traditionnelles en famille ?`,
    `伝統的な休日を家族とどのように祝いますか？`,
    `가족과 함께 전통적인 휴일을 어떻게 축하하나요?`,
    `你是如何和家人一起庆祝传统节日的？`,
    `Have you ever tried kimchi, a traditional Korean dish?`,
    `Avez-vous déjà essayé le kimchi, un plat coréen traditionnel ?`,
    `きんち、韓国の伝統料理を食べたことがありますか？`,
    `김치, 전통적인 한국 요리를 시도해 본 적이 있나요?`,
    `你有没有尝试过泡菜，一道传统的韩国菜？`,
    `What is the meaning of the phrase "hakuna matata" in Swahili?`,
    `Quelle est la signification de l'expression "hakuna matata" en swahili ?`,
    `スワヒリ語での「ハクナ・マタタ」の意味は何ですか？`,
    `스와힐리어에서 "하쿠나 마타타"라는 표현의 의미는 무엇인가요?`,
    `"Hakuna Matata" 在斯瓦希里语中的意思是什么？`,
    `Describe your favorite childhood memory.`,
    `Décrivez votre souvenir d'enfance préféré.`,
    `お気に入りの幼少期の思い出を説明してください。`,
    `가장 좋아하는 어린 시절의 기억을 설명해보세요.`,
    `描述一下你最喜欢的童年记忆。`,
    `How do you say "goodbye" in your native language?`,
    `Comment dit-on "au revoir" dans votre langue maternelle ?`,
    `あなたの母国語で「さようなら」と言いますか？`,
    `당신의 모국어로 "안녕"이라고 말하나요?`,
    `你的母语中怎么说“再见”？`,
    `Share a piece of advice that has had a significant impact on your life.`,
    `Partagez un conseil qui a eu un impact significatif sur votre vie.`,
    `あなたの人生に大きな影響を与えたアドバイスを共有してください。`,
    `당신의 삶에 큰 영향을 미친 조언을 나누어보세요.`,
    `分享一条对你生活产生重要影响的建议。`,
    `What is your favorite type of cuisine and why?`,
    `Quel est votre type de cuisine préféré et pourquoi ?`,
    `あなたの好きな料理は何ですか？なぜですか？`,
    `당신이 가장 좋아하는 요리 종류는 무엇이며 그 이유는 무엇인가요?`,
    `你最喜欢的菜系是什么，为什么？`,
    `Share a cultural tradition from your country that you find unique.`,
    `Partagez une tradition culturelle de votre pays que vous trouvez unique.`,
    `あなたの国から独自の文化的伝統を共有してください。`,
    `당신이 독특하다고 생각하는 국가의 문화적 전통을 나눠보세요.`,
    `分享你认为独特的你国文化传统。`,
    `How do you stay motivated when facing challenges?`,
    `Comment restez-vous motivé(e) face aux défis ?`,
    `難題に直面したときにどのようにモチベーションを保ちますか？`,
    `어려움에 직면했을 때 어떻게 동기부여를 유지하나요?`,
    `面对挑战时，你是如何保持动力的？`,
    `Describe a dream destination you would like to visit someday.`,
    `Décrivez une destination de rêve que vous aimeriez visiter un jour.`,
    `いつか訪れてみたい夢の目的地を説明してください。`,
    `언젠가 가보고 싶은 꿈의 여행지를 묘사해보세요.`,
    `描述一个你想要在某一天访问的梦幻目的地。`,
    `Do you have a favorite quote that inspires you?`,
    `Avez-vous une citation préférée qui vous inspire ?`,
    `あなたを刺激するお気に入りの引用文はありますか？`,
    `당신을 영감을 주는 좋아하는 인용구가 있나요?`,
    `你有一句激励你的最爱的名言吗？`,
    `Share a funny anecdote from your life.`,
    `Partagez une anecdote amusante de votre vie.`,
    `あなたの人生から面白い逸話を共有してください。`,
    `당신의 삶에서 웃긴 일화를 나눠보세요.`,
    `分享一则你生活中的搞笑趣事。`,
    `How do you handle stress and maintain a work-life balance?`,
    `Comment gérez-vous le stress et maintenez-vous un équilibre entre travail et vie personnelle ?`,
    `ストレスをどのように処理し、仕事と生活のバランスを保ちますか？`,
    `What is your favorite book, and why do you love it?`,
    `Quel est votre livre préféré, et pourquoi l'aimez-vous ?`,
    `お気に入りの本は何で、なぜそれを好きですか？`,
    `당신이 가장 좋아하는 책은 무엇이며 그 이유는 무엇인가요?`,
    `你最喜欢的书是什么，为什么喜欢它？`,
    `Describe a memorable travel experience you've had.`,
    `Décrivez une expérience de voyage mémorable que vous avez vécue.`,
    `思い出深い旅行の経験を説明してください。`,
    `기억에 남는 여행 경험을 설명해보세요.`,
    `描述一次你难忘的旅行经历。`,
    `How do you express gratitude in your culture?`,
    `Comment exprimez-vous la gratitude dans votre culture ?`,
    `あなたの文化で感謝の気持ちをどのように表現しますか？`,
    `당신의 문화에서 감사의 표현은 어떻게 하는지 알려주세요.`,
    `你在你的文化中是如何表达感激之情的？`,
    `Share a favorite childhood game or activity.`,
    `Partagez un jeu ou une activité préféré(e) de votre enfance.`,
    `お気に入りの幼少期のゲームや活動を共有してください。`,
    `어린 시절 좋아했던 게임이나 활동을 나눠보세요.`,
    `分享一个你小时候喜欢的游戏或活动。`,
    `What is a traditional dish from your country that you would recommend?`,
    `Quel est un plat traditionnel de votre pays que vous recommanderiez ?`,
    `おすすめするあなたの国の伝統料理は何ですか？`,
    `권장하고 싶은 당신 나라의 전통 요리는 무엇인가요?`,
    `你会推荐你国家的哪道传统菜？`,
    `If you could have dinner with any historical figure, who would it be?`,
    `Si vous pouviez dîner avec n'importe quelle figure historique, qui serait-ce ?`,
    `もし歴史上の人物と夕食を共にできるとしたら、誰と食事をしますか？`,
    `역사적 인물 중 누구와 저녁 식사를 하고 싶으신가요?`,
    `如果你能和任何历史人物一起共进晚餐，你会选择谁？`,
    `How do you celebrate birthdays in your culture?`,
    `Comment fêtez-vous les anniversaires dans votre culture ?`,
    `あなたの文化では誕生日をどのように祝いますか？`,
    `당신의 문화에서 생일을 어떻게 축하하나요?`,
    `你们文化中是如何庆祝生日的？`,
    `Share a favorite quote from a movie or a book.`,
    `Partagez une citation préférée d'un film ou d'un livre.`,
    `映画や本からのお気に入りの引用文を共有してください。`,
    `영화나 책에서 좋아하는 인용구를 나눠보세요.`,
    `分享一句你最喜欢的电影或书中的名言。`,
    `How do you stay productive during busy days?`,
    `Comment restez-vous productif(ve) pendant les journées chargées ?`,
    `忙しい日々においてどのように生産的でいるのですか？`,
    `바쁜 날에 생산적으로 어떻게 지내나요?`,
    `在繁忙的日子里你是如何保持高效的？`,
    `Describe a skill you've always wanted to learn.`,
    `Décrivez une compétence que vous avez toujours voulu apprendre.`,
    `ずっと学びたかったスキルを説明してください。`,
    `항상 배우고 싶었던 기술을 묘사해보세요.`,
    `描述一个你一直想学的技能。`,
    `Share a piece of advice you would give to your younger self.`,
    `Partagez un conseil que vous donneriez à votre jeune moi.`,
    `若い頃の自分にアドバイスするとしたら、どんなアドバイスをしますか？`,
    `어린 시절의 자기 자신에게 줄 조언을 나눠보세요.`,
    `如果你能给年轻的自己一个建议，那会是什么？`,
    `What is your favorite type of art, and why?`,
    `Quel est votre type d'art préféré, et pourquoi ?`,
    `お気に入りのアートの形式は何で、なぜですか？`,
    `당신이 가장 좋아하는 예술 형식은 무엇이며 왜 그런가요?`,
    `你最喜欢的艺术形式是什么，为什么？`,
    `How do you handle setbacks and keep moving forward?`,
    `Comment gérez-vous les revers et continuez d'avancer ?`,
    `逆境をどのように乗り越えて前進しますか？`,
    `어떻게 역경을 처리하고 계속 나아가나요?`,
    `你是如何处理挫折并继续前进的？`,
    `Share a favorite childhood toy or game.`,
    `Partagez un jouet ou un jeu préféré(e) de votre enfance.`,
    `お気に入りの幼少期のおもちゃやゲームを共有してください。`,
    `어린 시절 좋아했던 장난감이나 게임을 나눠보세요.`,
    `分享一个你小时候喜欢的玩具或游`,
    `What is a traditional festival celebrated in your country?`,
    `Quelle est la fête traditionnelle célébrée dans votre pays ?`,
    `あなたの国で祝われている伝統的な祭りは何ですか？`,
    `당신의 나라에서 기념되는 전통 축제는 무엇인가요?`,
    `你们国家有哪个传统节日？`,
    `Share a childhood memory associated with a favorite food.`,
    `Partagez un souvenir d'enfance associé à votre plat préféré.`,
    `お気に入りの食べ物に関連する幼少期の思い出を共有してください。`,
    `좋아하는 음식과 관련된 어린 시절의 기억을 나눠보세요.`,
    `分享一个与喜欢的食物相关的童年记忆。`,
    `If you could have any superpower, what would it be and why?`,
    `Si vous pouviez avoir n'importe quel superpouvoir, lequel serait-ce et pourquoi ?`,
    `もし超能力を持てるとしたら、何が欲しいですか？なぜですか？`,
    `만약 어떤 슈퍼파워라도 가질 수 있다면 어떤 것이며 그 이유는 무엇인가요?`,
    `如果你可以拥有任何超能力，那会是什么，为什么？`,
    `Describe a favorite spot in nature that brings you peace.`,
    `Décrivez un endroit préféré dans la nature qui vous apporte la paix.`,
    `あなたに平和をもたらす自然の中のお気に入りの場所を説明してください。`,
    `당신에게 평온을 가져다주는 자연 속의 즐겨찾는 장소를 묘사해보세요.`,
    `描述一个让你感到宁静的大自然中的最爱之地。`,
    `How do you like to spend your weekends?`,
    `Comment aimez-vous passer vos week-ends ?`,
    `週末はどのように過ごすのが好きですか？`,
    `주말을 어떻게 보내는 것을 좋아하나요?`,
    `你喜欢如何度过周末？`,
    `Share a favorite piece of music and its significance to you.`,
    `Partagez une pièce musicale préférée et sa signification pour vous.`,
    `お気に入りの音楽の一曲と、それがあなたにとってどんな意味を持っているかを共有してください。`,
    `좋아하는 음악 조각과 그것이 당신에게 어떤 의미가 있는지를 나눠보세요.`,
    `分享一首你喜欢的音乐以及它对你的重要性。`,
    `What is a popular tradition during New Year's in your culture?`,
    `Quelle est une tradition populaire pendant le Nouvel An dans votre culture ?`,
    `あなたの文化でのお正月における人気のある伝統は何ですか？`,
    `당신의 문화에서는 새해에 인기 있는 전통이 무엇인가요?`,
    `在你的文化中，新年期间有哪些流行的传统？`,
    `Describe a place you've always wanted to visit but haven't yet.`,
    `Décrivez un endroit que vous avez toujours voulu visiter mais que vous n'avez pas encore fait.`,
    `まだ訪れたことのないけれどずっと行きたかった場所を説明してください。`,
    `아직 가보지 못한데 항상 가고 싶었던 곳을 묘사해보세요.`,
    `描述一个你一直想去但尚未拜访的地方。`,
    `If you could time travel, what era would you visit and why?`,
    `Si vous pouviez voyager dans le temps, quelle époque visiteriez-vous et pourquoi ?`,
    `タイムトラベルができるとしたら、どの時代に行きたいですか？なぜですか？`,
    `만약 시간 여행이 가능하다면 어떤 시대로 가고 싶으며 그 이유는 무엇인가요?`,
    `如果你能时光穿梭，你会选择访问哪个时代，为什么？`,
    `How do you express creativity in your daily life?`,
    `Comment exprimez-vous la créativité dans votre vie quotidienne ?`,
    `日常生活でどのように創造性を表現しますか？`,
    `당신은 일상생활에서 어떻게 창의성을 표현하나요?`,
    `你是如何在日常生活中表达创造力的？`,
    `Share a memorable experience from a live performance or concert.`,
    `Partagez une expérience mémorable d'un spectacle ou d'un concert en direct.`,
    `ライブパフォーマンスやコンサートの思い出深い経験を共有してください。`,
    `라이브 공연이나 콘서트에서의 기억에 남는 경험을 나눠보세요.`,
    `分享一次你在现场演出或音乐会上的难忘经历。`,
    `How do you stay connected with friends and family in the digital age?`,
    `Comment restez-vous en contact avec vos amis et votre famille à l'ère numérique ?`,
    `デジタル時代において友達や家族とどのように繋がりを保ちますか？`,
    `디지털 시대에 친구와 가족과 어`,
    `Share a recipe for a dish you enjoy cooking.`,
    `Partagez une recette pour un plat que vous aimez cuisiner.`,
    `あなたが楽しく料理する料理のレシピを教えてください。`,
    `당신이 즐겨 만드는 요리의 레시피를 나눠보세요.`,
    `分享一个你喜欢做的菜的食谱。`,
    `If you could learn any instrument, which one would it be and why?`,
    `Si vous pouviez apprendre n'importe quel instrument, lequel serait-ce et pourquoi ?`,
    `もし任意の楽器を学べるとしたら、どれを学びたいですか？なぜですか？`,
    `만약 어떤 악기든 배울 수 있다면 어떤 것을 배우고 싶으며 그 이유는 무엇인가요?`,
    `如果你可以学习任何乐器，你会选择哪个，为什么？`,
    `Share a funny language misunderstanding you've experienced.`,
    `Partagez un malentendu linguistique amusant que vous avez vécu.`,
    `おもしろい言語の誤解を教えてください。`,
    `당신이 경험한 웃긴 언어 오해를 나눠보세요.`,
    `分享一个你曾经经历过的有趣语言误解。`,
    `Describe a cultural event or festival you've attended.`,
    `Décrivez un événement ou un festival culturel auquel vous avez assisté.`,
    `参加した文化イベントや祭りを説明してください。`,
    `참석한 문화 행사나 축제에 대해 설명해보세요.`,
    `描述一个你参加过的文化活动或节庆。`,
    `How do you handle stress at work or in your studies?`,
    `Comment gérez-vous le stress au travail ou dans vos études ?`,
    `仕事や勉強中のストレスをどのように処理しますか？`,
    `직장이나 공부 중의 스트레스를 어떻게 다루나요?`,
    `你在工作或学习中如何处理压力？`,
    `Share a favorite childhood bedtime story or fairytale.`,
    `Partagez une histoire préférée de votre enfance à lire avant de dormir.`,
    `幼少期のお気に入りの寝る前のお話やおとぎ話を教えてください。`,
    `어린 시절 좋아했던 자장가 이야기나 동화를 나눠보세요.`,
    `分享一个你小时候喜欢的睡前故事或童话。`,
    `If you could have dinner with any fictional character, who would it be?`,
    `Si vous pouviez dîner avec n'importe quel personnage fictif, qui serait-ce ?`,
    `もし架空のキャラクターと夕食を共にできるとしたら、誰と食事をしますか？`,
    `만약 허구의 캐릭터와 저녁 식사를 할 수 있다면 누구와 하고 싶으신가요?`,
    `如果你能和任何虚构角色一起共进晚餐，你会选择谁？`,
    `Describe a favorite winter activity or sport you enjoy.`,
    `Décrivez une activité ou un sport d'hiver que vous aimez particulièrement.`,
    `お気に入りの冬のアクティビティやスポーツを説明してください。`,
    `당신이 즐겨 하는 겨울 활동이나 스포츠를 묘사해보세요.`,
    `描述一项你喜欢的冬季活动或运动。`,
    `How do you celebrate achievements or milestones in your life?`,
    `Comment célébrez-vous les réalisations ou les étapes importantes de votre vie ?`,
    `人生の成果や節目をどのように祝いますか？`,
    `당신의 삶에서의 성취나 이정표를 어떻게 축하하나요?`,
    `你是如何庆祝生活中的成就或重要时刻的？`,
    `Share a favorite quote from a historical figure and its significance to you.`,
    `Partagez une citation préférée d'une figure historique et sa signification pour vous.`,
    `歴史上の人物の好きな引用文と、それがあなたにとってどんな意味を持っているかを共有してください。`,
    `역사적 인물 중 좋아하는 인용구와 그것이 당신에게 어떤 의미가 있는지를 나눠보세요.`,
    `分享一个你喜欢的历史人物的名言及其对你的重要性。`,
    `How do you stay physically active and maintain a healthy lifestyle?`,
    `Comment restez-vous physiquement actif(ve) et maintenez-vous un mode de vie sain ?`,
    `体を動かし、健康的なライフスタイルを維持するためにどのようにしていますか？`,
    `어떻게 신체적으로 활동적이고 건강한 생활 방식을 유지하나요?`,
    `你是如何保持身体活跃并维持健康生活方式的？`,
    `Share a favorite memory from a family gathering or reunion.`,
    `Partagez un souvenir préféré d'une réunion ou d'une réunion familiale.`,
    `家族の集まりや再会の中でのお気に入りの思い出を共有してください。`,
    `가족이 모여 있는 행사나 상봉에서의 좋아하는 기억을 나눠보세요.`,
    `分享一个在家庭聚会或团聚中的喜悦时刻。`,
    `If you could visit any historical era, where would you go and why?`,
    `Si vous pouviez visiter n'importe quelle époque historique, où iriez-vous et pourquoi ?`,
    `もし歴史の中のどの時代に訪れることができるとしたら、どこに行きたいですか？なぜですか？`,
    `만약 어떤 역사적 시대라도 방문할 수 있다면 어디로 가고 싶으며 그 이유는 무엇인가요?`,
    `如果你能访问任何历史时代，你会选择去哪里，为什么？`,
    `Describe a favorite place in your hometown or where you currently live.`,
    `Décrivez un endroit préféré dans votre ville natale ou là où vous habitez actuellement.`,
    `あなたの故郷や現在の住んでいる場所でのお気に入りの場所を説明してください。`,
    `당신의 고향이나 현재 거주하는 곳에서의 좋아하는 장소를 묘사해보세요.`,
    `描述一下你家乡或现居地的一个喜欢的地方。`,
    `Share a favorite quote that reflects your personal philosophy.`,
    `Partagez une citation préférée qui reflète votre philosophie personnelle.`,
    `あなたの個人的な哲学を反映するお気に入りの引用文を共有してください。`,
    `당신의 개인 철학을 반영하는 좋아하는 인용구를 나눠보세요.`,
    `分享一句反映你个人哲学的最爱的名言。`,
    `How do you handle moments of uncertainty or change in your life?`,
    `Comment gérez-vous les moments d'incertitude ou de changement dans votre vie ?`,
    `人生の不確実性や変化の瞬間をどのように処理しますか？`,
    `당신의 삶에서 불확실성이나 변화의 순간을 어떻게 다루나요?`,
    `你在生活中如何处理不确定或变化的时刻？`,
    `Describe a cultural tradition related to weddings in your community.`,
    `Décrivez une tradition culturelle liée aux mariages dans votre communauté.`,
    `あなたのコミュニティにおける結婚に関連する文化的な伝統を説明してください。`,
    `당신의 지역 사회에서 결혼과 관련된 문화적 전통을 묘사해보세요.`,
    `描述一种与你社区婚礼相关的文化传统。`,
    `If you could learn any language instantly, which one would it be and why?`,
    `Si vous pouviez apprendre instantanément n'importe quelle langue, laquelle serait-ce et pourquoi ?`,
    `即座にどの言語でも瞬時に学ぶことができるとしたら、どの言語を選びますか？なぜですか？`,
    `당신이 즉시 어떤 언어든지 배울 수 있다면 어떤 언어를 선택하고 그 이유는 무엇인가요?`,
    `如果你能瞬间学会任何一种语言，你会选择哪一种，为什么？`,
    `Share a favorite quote about the importance of friendship.`,
    `Partagez une citation préférée sur l'importance de l'amitié.`,
    `友情の重要性についてのお気に入りの引用文を共有してください。`,
    `친구의 중요성에 관한 좋아하는 인용구를 나눠보세요.`,
    `分享一句关于友谊重要性的最爱的名言。`,
    `How do you balance work or study with personal hobbies and interests?`,
    `Comment équilibrez-vous le travail ou les études avec vos loisirs et intérêts personnels ?`,
    `仕事や勉強と個人の趣味や興味をどのように調和させていますか？`,
    `업무 또는 공부와 개인적인 취미와 관심사를 어떻게 균형있게 유지하나요?`,
    `你是如何在工作或学习与个人爱好和兴趣之间保持平衡的？`,
    `Share a memorable experience from a volunteering or community service activity.`,
    `Partagez une expérience mémorable d'une activité bénévole ou de service communautaire.`,
    `If you could have a conversation with any historical figure, who would it be?`,
    `Si vous pouviez avoir une conversation avec n'importe quelle figure historique, qui serait-ce ?`,
    `もし歴史上の人物と会話できるとしたら、誰と話しますか？`,
    `만약 어떤 역사적 인물이랑 대화할 수 있다면 누구와 대화하고 싶으신가요?`,
    `如果你能与任何历史人物交谈，你会选择谁？`,
    `Share a favorite memory from a school trip or educational experience.`,
    `Partagez un souvenir préféré d'un voyage scolaire ou d'une expérience éducative.`,
    `学校の遠足や教育体験からのお気に入りの思い出を共有してください。`,
    `학교 여행이나 교육적 경험 중에서 기억에 남는 좋아하는 순간을 나눠보세요.`,
    `分享一次学校旅行或教育经历中的喜悦时刻。`,
    `How do you stay motivated when pursuing long-term goals?`,
    `Comment restez-vous motivé(e) lorsque vous poursuivez des objectifs à long terme ?`,
    `長期目標を追求する際にどのようにモチベーションを維持しますか？`,
    `장기 목표를 달성하기 위해 어떻게 동기를 유지하나요?`,
    `在追求长期目标时，你是如何保持动力的？`,
    `Share a favorite piece of advice you've received from someone.`,
    `Partagez un conseil préféré que vous avez reçu de quelqu'un.`,
    `誰かからもらったお気に入りのアドバイスを共有してください。`,
    `누군가로부터 받은 좋아하는 조언을 나눠보세요.`,
    `分享一条你从他人那里得到的最爱的建议。`,
    `Describe a moment when you faced a fear and overcame it.`,
    `Décrivez un moment où vous avez fait face à une peur et l'avez surmontée.`,
    `恐れに立ち向かい、それを克服した瞬間を説明してください。`,
    `어떤 공포에 직면하고 이겨낸 순간을 묘사해보세요.`,
    `描述一次你面对恐惧并克服它的时刻。`,
    `If you could have any animal as a companion, which one would it be?`,
    `Si vous pouviez avoir n'importe quel animal comme compagnon, lequel serait-ce ?`,
    `どんな動物を仲間にしたいですか？`,
    `만약 동물을 동반자로 가질 수 있다면 어떤 동물을 선택하고 싶으신가요?`,
    `如果你能选择任何动物作为伴侣，你会选择哪个？`,
    `If you could meet any historical figure and have a conversation, who would it be?`,
    `Si vous pouviez rencontrer n'importe quelle figure historique et avoir une conversation, qui serait-ce ?`,
    `もし歴史上の人物と会話ができるとしたら、誰と会いたいですか？`,
    `만약 역사적 인물 중 누구와 대화할 수 있다면 누구와 만나고 싶으신가요?`,
    `如果你能与任何历史人物会面并进行对话，你会选择谁？`,
    `Describe a favorite piece of art or sculpture and its significance to you.`,
    `Décrivez une œuvre d'art ou une sculpture préférée et sa signification pour vous.`,
    `お気に入りの美術作品や彫刻を説明して、それがあなたにとってどんな意味を持っているかを教えてください。`,
    `당신이 좋아하는 미술작품이나 조각품을 묘사하고 그것이 당신에게 어떤 의미가 있는지 나눠보세요.`,
    `描述一个你最喜欢的艺术品或雕塑以及它对你的重要性。`,
    `Share a favorite memory from a school or university experience.`,
    `Partagez un souvenir préféré d'une expérience scolaire ou universitaire.`,
    `学校や大学の経験からのお気に入りの思い出を共有してください。`,
]

module.exports = sentences;