const arr = [
    "Tôi xin phản ánh về việc tài khoản email bị vô hiệu hóa một cách đột ngột. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi rất bất ngờ khi nhận được thông báo rằng tài khoản email của tôi đã bị tắt. Mong bạn mở lại tài khoản này và tôi xin chân thành cảm ơn.",
    "Việc tài khoản email của tôi bị vô hiệu hóa đã gây rất nhiều phiền toái. Tôi mong bạn khắc phục sự cố này và tôi xin chân thành cảm ơn.",
    "Xin lưu ý rằng việc tài khoản email của tôi bị tắt đã gây trở ngại lớn cho công việc hàng ngày của tôi. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi không thể tiếp tục công việc và giao tiếp hiệu quả nếu tài khoản email của tôi không được mở lại. Mong bạn xem xét và tôi xin chân thành cảm ơn.",
    "Tôi rất cần thiết truy cập vào email để hoàn thành các nhiệm vụ quan trọng. Tôi kính mong bạn mở lại tài khoản này và tôi xin chân thành cảm ơn.",
    "Tài khoản email của tôi đã bị vô hiệu hóa mà không có thông báo trước. Tôi đề nghị mở lại tài khoản và tôi xin chân thành cảm ơn sự hỗ trợ của bạn.",
    "Sự vô hiệu hóa tài khoản email đã làm mất đi khả năng liên lạc và truy cập vào thông tin quan trọng. Xin hãy mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã mất đi cơ hội quan trọng vì tài khoản email không hoạt động. Tôi rất cần sự khắc phục và tôi xin chân thành cảm ơn.",
    "Tôi đang gặp khó khăn lớn do tài khoản email bị tắt. Mong bạn mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Việc vô hiệu hóa tài khoản email đã ảnh hưởng tiêu cực đến công việc của tôi. Mong bạn mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã mất đi cơ hội quan trọng trong việc liên lạc và giao tiếp do tài khoản email bị tắt. Xin vui lòng khắc phục và tôi xin chân thành cảm ơn.",
    "Việc tài khoản email bị vô hiệu hóa đã gây phiền toái và ảnh hưởng đến sự liên kết của tôi với khách hàng. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi rất cần truy cập vào email để xử lý các vấn đề khẩn cấp. Mong bạn khôi phục tài khoản này và tôi xin chân thành cảm ơn.",
    "Việc tài khoản email bị tắt đã gây ra sự bất tiện lớn và ảnh hưởng xấu đến công việc của tôi. Xin vui lòng khắc phục sự cố và tôi xin chân thành cảm ơn.",
    "Tài khoản email của tôi đã bị vô hiệu hóa, điều này đã gây khó khăn đáng kể trong việc truyền thông và quản lý công việc. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Việc mất khả năng truy cập vào tài khoản email đã gây mất đi một số thông tin quan trọng. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi không thể tiếp tục công việc một cách hiệu quả nếu tài khoản email của tôi không được mở lại. Xin vui lòng xem xét và tôi xin chân thành cảm ơn.",
    "Tôi rất cần tài khoản email để giữ liên lạc và thực hiện các nhiệm vụ quan trọng. Xin vui lòng khôi phục tài khoản này và tôi xin chân thành cảm ơn.",
    "Việc vô hiệu hóa tài khoản email đã gây mất đi cơ hội kinh doanh quan trọng. Tôi mong bạn mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email của tôi là công cụ quan trọng để duy trì liên lạc với đồng nghiệp và đối tác. Mong bạn khắc phục tình trạng này và tôi xin chân thành cảm ơn.",
    "Tôi rất phụ thuộc vào email để nhận thông báo và tài liệu quan trọng. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Việc mất đi tài khoản email đã gây thiệt hại cho sự uy tín và hình ảnh cá nhân của tôi. Mong bạn khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email là phương tiện duy nhất để tôi liên lạc với gia đình và bạn bè ở xa. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã mất đi quyền truy cập vào hòm thư chứa các thông tin quan trọng. Xin vui lòng khắc phục tình trạng này và tôi xin chân thành cảm ơn.",
    "Tài khoản email bị tắt đã gây mất đi khả năng chia sẻ tài liệu và hợp tác trong công việc. Mong bạn mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã đăng ký nhiều dịch vụ trực tuyến bằng email của mình. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Việc mất đi tài khoản email đã gây khó khăn trong việc kiểm soát thông tin cá nhân. Mong bạn khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi rất cần email để xử lý các vấn đề tài chính và hành chính cá nhân. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi không thể gửi hoặc nhận email vì tài khoản của tôi đã bị vô hiệu hóa. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc vô hiệu hóa tài khoản email đã ảnh hưởng đến công việc hàng ngày của tôi. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Email là phương tiện chính để tôi liên lạc và nhận thông tin quan trọng. Mong bạn khắc phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email bị tắt đã gây rất nhiều bất tiện và mất thời gian. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã mất đi một số email quan trọng vì tài khoản bị disable. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc không thể truy cập vào tài khoản email đã gây rối loạn trong việc quản lý công việc của tôi. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Email là cầu nối quan trọng giữa tôi và khách hàng. Mong bạn khắc phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email của tôi là công cụ quan trọng để giao tiếp và chia sẻ thông tin. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc mất đi tài khoản email đã gây rối loạn trong việc truyền thông với đồng nghiệp. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã không thể truy cập vào tài khoản email trong một thời gian dài. Xin vui lòng khắc phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi rất bất ngờ khi phát hiện tài khoản email của tôi bị vô hiệu hóa. Mong bạn mở lại tài khoản này và tôi xin chân thành cảm ơn.",
    "Việc tài khoản email bị tắt đã làm gián đoạn quá trình làm việc của tôi. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi cần khôi phục tài khoản email ngay lập tức để tiếp tục giao tiếp và truyền thông. Xin vui lòng hỗ trợ và tôi xin chân thành cảm ơn.",
    "Việc mất đi truy cập vào tài khoản email đã gây khó khăn trong việc quản lý thông tin cá nhân và công việc. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email của tôi đã bị vô hiệu hóa một cách bất ngờ, gây trở ngại đáng kể trong công việc. Mong bạn mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Việc không thể truy cập vào tài khoản email đã ảnh hưởng tiêu cực đến việc nhận thông tin quan trọng. Xin vui lòng khắc phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi không thể truy cập vào email từ khi tài khoản bị disable. Mong bạn khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc mất đi tài khoản email đã gây rối loạn trong việc giao tiếp và hợp tác với đồng nghiệp. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email là công cụ cần thiết trong công việc của tôi. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Việc vô hiệu hóa tài khoản email đã gây trở ngại đáng kể trong việc gửi và nhận thông tin quan trọng. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã không thể truy cập vào tài khoản email suốt một thời gian dài. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc vô hiệu hóa tài khoản email đã ảnh hưởng nghiêm trọng đến việc giao tiếp và liên lạc. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email của tôi đã bị vô hiệu hóa mà không có thông báo trước. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc mất đi truy cập vào tài khoản email đã gây trở ngại lớn trong việc quản lý thông tin cá nhân và công việc. Mong bạn mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi cần khôi phục tài khoản email để tiếp tục giao tiếp và truyền thông một cách bình thường. Xin vui lòng hỗ trợ và tôi xin chân thành cảm ơn.",
    "Việc không thể truy cập vào tài khoản email đã ảnh hưởng tiêu cực đến khả năng liên lạc với đồng nghiệp và khách hàng. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tài khoản email của tôi là công cụ quan trọng trong việc quản lý công việc hàng ngày. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc mất đi truy cập vào tài khoản email đã gây trở ngại lớn trong việc nhận và xử lý thông tin quan trọng. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn.",
    "Tôi đã mất đi quyền truy cập vào hòm thư chứa các thông tin quan trọng. Xin vui lòng khôi phục tài khoản và tôi xin chân thành cảm ơn.",
    "Việc vô hiệu hóa tài khoản email đã làm gián đoạn quá trình làm việc và giao tiếp của tôi. Xin vui lòng mở lại tài khoản và tôi xin chân thành cảm ơn."
]
function getConplaint() {
    const randomIndex = Math.floor(Math.random() * arr.length);
    return arr[randomIndex];
}
const reportDisableMail = {
    getConplaint
}
module.exports = reportDisableMail;